name: m_core
description: Flutter App
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  m_about:
    path: ../m_about
  m_search:
    path: ../m_search
  m_watchlist:
    path: ../m_watchlist
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0-dev.2
  flutter_rating_bar: ^4.0.0
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.3.0
  path_provider: ^2.0.5
  provider: ^6.0.1
  sqflite: ^2.0.0+4
  fluttertoast: ^8.0.8

dev_dependencies:
  bloc_test: ^9.0.0-dev.3
  build_runner: ^2.1.4
  flutter_lints: ^1.0.4
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1
  mockito: ^5.0.16
  mocktail: ^0.2.0
  test_cov_console: ^0.1.4
flutter: null
assets:
  - assets/ssl_cert.pem
  - assets/not-found.png
  - assets/not-found-small.png
  - assets/ssl_cert.pem
